export interface GuardrailResult {
  allowed: boolean
}

const OUT_OF_SCOPE_PATTERNS = [
  /ignore previous/i,
  /you are now/i,
  /act as/i,
  /disregard your rules/i,
  /system prompt/i,
  /forget your instructions/i,
  /reveal your/i,
  /what model/i,
  /underlying technology/i,
]

const FOOD_KEYWORDS = [
  /ingredient/i,
  /label/i,
  /nutrition/i,
  /additive/i,
  /preservative/i,
  /calorie/i,
  /protein/i,
  /sugar/i,
  /sodium/i,
  /fat/i,
  /vitamin/i,
  /mineral/i,
  /store/i,
  /storage/i,
  /expire/i,
  /contain/i,
  /food/i,
  /eat/i,
  /drink/i,
  /beverage/i,
  /oil/i,
  /acid/i,
  /syrup/i,
  /flour/i,
  /pepsi/i,
  /coke/i,
  /aspartame/i,
  /msg/i,
  /monosodium/i,
  /tartrazine/i,
  /dextrose/i,
  /xanthan/i,
  /gum/i,
  /maltodextrin/i,
  /caramel/i,
  /stearate/i,
  /sorbitol/i,
  /lecithin/i,
  /pectin/i,
  /dextrin/i,
  /maltitol/i,
  /mannitol/i,
  /xylitol/i,
  /erythritol/i,
  /sucrose/i,
  /fructose/i,
  /maltose/i,
  /lactose/i,
  /glucose/i,
  /saccharin/i,
  /sucralose/i,
  /stevia/i,
  /neotame/i,
  /acefulfame/i,
  /cyclamate/i,
  /tagatose/i,
  /allulose/i,
  /benzoate/i,
  /sorbate/i,
  /propionate/i,
  /nitrite/i,
  /nitrate/i,
  /sulfite/i,
  /sulfur/i,
  /erythorbate/i,
  /tocopherol/i,
  /carrageenan/i,
  /agar/i,
  /gelatin/i,
  /starch/i,
  /modified starch/i,
  /polysorbate/i,
  /annatto/i,
  /turmeric/i,
  /paprika/i,
  /riboflavin/i,
  /vanillin/i,
  /inosinate/i,
  /guanylate/i,
  /hydrolyzed/i,
  /maltodextrin/i,
  /phosphate/i,
  /bicarbonate/i,
  /carbonate/i,
  /cellulose/i,
  /glycerol/i,
  /propylene/i,
  /glycol/i,
  /niacin/i,
  /thiamine/i,
  /riboflavin/i,
  /folate/i,
  /folic/i,
  /choline/i,
  /inositol/i,
  /coenzyme/i,
  /omega.?3/i,
  /omega.?6/i,
  /trans.?fat/i,
  /saturated.?fat/i,
  /unsaturated.?fat/i,
  /monounsaturated/i,
  /polyunsaturated/i,
  /hydrogenated/i,
  /partially.?hydrogenated/i,
  /interesterified/i,
  /palm.?oil/i,
  /coconut.?oil/i,
  /canola/i,
  /sunflower.?oil/i,
  /soybean.?oil/i,
  /olive.?oil/i,
  /peanut.?oil/i,
  /vegetable.?oil/i,
  /cholesterol/i,
  /calcium/i,
  /magnesium/i,
  /potassium/i,
  /zinc/i,
  /copper/i,
  /manganese/i,
  /selenium/i,
  /iodine/i,
  /ferrous/i,
  /sulfate/i,
  /carbohydrate/i,
  /carb$/i,
  /fibre/i,
  /fiber/i,
  /cereal/i,
  /bread/i,
  /rice/i,
  /pasta/i,
  /noodle/i,
  /biscuit/i,
  /cookie/i,
  /cake/i,
  /chocolate/i,
  /candy/i,
  /yogurt/i,
  /yoghurt/i,
  /cheese/i,
  /milk/i,
  /cream/i,
  /butter/i,
  /margarine/i,
  /sauce/i,
  /gravy/i,
  /soup/i,
  /snack/i,
  /chip/i,
  /cracker/i,
  /gum/i,
  /nut/i,
  /seed/i,
  /legume/i,
  /bean/i,
  /lentil/i,
  /soy/i,
  /tofu/i,
  /tempeh/i,
  /meat/i,
  /poultry/i,
  /fish/i,
  /seafood/i,
  /egg/i,
  /fruit/i,
  /vegetable/i,
  /herb/i,
  /spice/i,
  /garri/i,
  /eba/i,
  /fufu/i,
  /amala/i,
  /yam/i,
  /cassava/i,
  /cocoyam/i,
  /plantain/i,
  /groundnut/i,
  /stockfish/i,
  /crayfish/i,
  /maggi/i,
  /seasoning/i,
  /indomie/i,
  /noodle/i,
  /milo/i,
  /bournvita/i,
  /ovaltine/i,
  /evaporated.?milk/i,
  /condensed.?milk/i,
  /powdered.?milk/i,
  /antioxidant/i,
  /emulsifier/i,
  /stabilizer/i,
  /stabiliser/i,
  /thickener/i,
  /humectant/i,
  /bulking.?agent/i,
  /raising.?agent/i,
  /anti.?caking/i,
  /glazing.?agent/i,
  /firming.?agent/i,
  /flavour/i,
  /flavor/i,
  /colour/i,
  /color/i,
  /sweetener/i,
  /dietary.?fib/i,
  /dietary.?fibe/i,
  /enzym/i,
  /protein/i,
  /carbohydrate/i,
  /ingredient/i,
  /additive/i,
  /lactose/i,
  /gluten/i,
  /wheat/i,
  /maize/i,
  /corn/i,
  /barley/i,
  /oat/i,
  /rye/i,
  /millet/i,
  /sorghum/i,
  /yeast/i,
  /baking.?soda/i,
  /baking.?powder/i,
  /mono.?and.?diglyceride/i,
  /sodium/i,
  /potassium/i,
  /calcium/i,
  /magnesium/i,
]

export function sanitizeInput(input: string): string {
  return input.replace(/[<>]/g, "").replace(/[{}`$]/g, "").trim()
}

export function runGuardrail(input: string, isFollowUp = false): GuardrailResult {
  const cleanInput = sanitizeInput(input)

  const isInjection = OUT_OF_SCOPE_PATTERNS.some((p) => p.test(cleanInput))
  if (isInjection) return { allowed: false }

  if (!isFollowUp) {
    const isFoodRelated = FOOD_KEYWORDS.some((p) => p.test(cleanInput))
    if (!isFoodRelated) return { allowed: false }
  }

  return { allowed: true }
}
