export interface GuardrailResult {
  allowed: boolean
}

const OUT_OF_SCOPE_PATTERNS = [
  /ignore previous/i,
  /you are now/i,
  /act as/i,
  /disregard your rules/i,
  /system prompt/i,
  /forget your instructions/i,
  /reveal your/i,
  /what model/i,
  /underlying technology/i,
]

const UNRELATED_TOPICS = [
  /weather/i,
  /forecast/i,
  /coding/i,
  /programming/i,
  /sport/i,
  /football/i,
  /basketball/i,
  /soccer/i,
  /music/i,
  /movie/i,
  /film/i,
]

const FOOD_BRANDS = [
  /indomie/i, /gala/i, /chi exotic/i, /lacasera/i, /bigi/i,
  /pepsi/i, /sprite/i, /coca cola/i, /coke/i, /fanta/i,
  /milo/i, /bournvita/i, /ovaltine/i, /peak milk/i, /hollandia/i,
  /nasco/i, /digestive/i, /cabin/i, /digestives/i, /ribena/i,
  /lucozade/i, /maltina/i, /hi malt/i, /amstel/i, /trophy/i,
  /golden morn/i, /cornflakes/i, /quaker/i, /nutri/i,
]

const FOOD_KEYWORDS = [
  /ingredient/i,
  /label/i,
  /nutrition/i,
  /additive/i,
  /preservative/i,
  /calorie/i,
  /protein/i,
  /sugar/i,
  /sodium/i,
  /fat/i,
  /vitamin/i,
  /mineral/i,
  /store/i,
  /storage/i,
  /expire/i,
  /contain/i,
  /food/i,
  /eat/i,
  /drink/i,
  /beverage/i,
  /oil/i,
  /acid/i,
  /syrup/i,
  /flour/i,
  /pepsi/i,
  /coke/i,
  /aspartame/i,
  /msg/i,
  /monosodium/i,
  /tartrazine/i,
  /dextrose/i,
  /xanthan/i,
  /gum/i,
  /maltodextrin/i,
  /caramel/i,
  /stearate/i,
  /sorbitol/i,
  /lecithin/i,
  /pectin/i,
  /dextrin/i,
  /maltitol/i,
  /mannitol/i,
  /xylitol/i,
  /erythritol/i,
  /sucrose/i,
  /fructose/i,
  /maltose/i,
  /lactose/i,
  /glucose/i,
  /saccharin/i,
  /sucralose/i,
  /stevia/i,
  /neotame/i,
  /acefulfame/i,
  /cyclamate/i,
  /tagatose/i,
  /allulose/i,
  /benzoate/i,
  /sorbate/i,
  /propionate/i,
  /nitrite/i,
  /nitrate/i,
  /sulfite/i,
  /sulfur/i,
  /erythorbate/i,
  /tocopherol/i,
  /carrageenan/i,
  /agar/i,
  /gelatin/i,
  /starch/i,
  /modified starch/i,
  /polysorbate/i,
  /annatto/i,
  /turmeric/i,
  /paprika/i,
  /riboflavin/i,
  /vanillin/i,
  /inosinate/i,
  /guanylate/i,
  /hydrolyzed/i,
  /maltodextrin/i,
  /phosphate/i,
  /bicarbonate/i,
  /carbonate/i,
  /cellulose/i,
  /glycerol/i,
  /propylene/i,
  /glycol/i,
  /niacin/i,
  /thiamine/i,
  /riboflavin/i,
  /folate/i,
  /folic/i,
  /choline/i,
  /inositol/i,
  /coenzyme/i,
  /omega.?3/i,
  /omega.?6/i,
  /trans.?fat/i,
  /saturated.?fat/i,
  /unsaturated.?fat/i,
  /monounsaturated/i,
  /polyunsaturated/i,
  /hydrogenated/i,
  /partially.?hydrogenated/i,
  /interesterified/i,
  /palm.?oil/i,
  /coconut.?oil/i,
  /canola/i,
  /sunflower.?oil/i,
  /soybean.?oil/i,
  /olive.?oil/i,
  /peanut.?oil/i,
  /vegetable.?oil/i,
  /cholesterol/i,
  /calcium/i,
  /magnesium/i,
  /potassium/i,
  /zinc/i,
  /copper/i,
  /manganese/i,
  /selenium/i,
  /iodine/i,
  /ferrous/i,
  /sulfate/i,
  /carbohydrate/i,
  /carb$/i,
  /fibre/i,
  /fiber/i,
  /cereal/i,
  /bread/i,
  /rice/i,
  /pasta/i,
  /noodle/i,
  /biscuit/i,
  /cookie/i,
  /cake/i,
  /chocolate/i,
  /candy/i,
  /yogurt/i,
  /yoghurt/i,
  /cheese/i,
  /milk/i,
  /cream/i,
  /butter/i,
  /margarine/i,
  /sauce/i,
  /gravy/i,
  /soup/i,
  /snack/i,
  /chip/i,
  /cracker/i,
  /gum/i,
  /nut/i,
  /seed/i,
  /legume/i,
  /bean/i,
  /lentil/i,
  /soy/i,
  /tofu/i,
  /tempeh/i,
  /meat/i,
  /poultry/i,
  /fish/i,
  /seafood/i,
  /egg/i,
  /fruit/i,
  /vegetable/i,
  /herb/i,
  /spice/i,
  /garri/i,
  /eba/i,
  /fufu/i,
  /amala/i,
  /yam/i,
  /cassava/i,
  /cocoyam/i,
  /plantain/i,
  /groundnut/i,
  /stockfish/i,
  /crayfish/i,
  /maggi/i,
  /knorr/i,
  /royco/i,
  /seasoning/i,
  /indomie/i,
  /noodle/i,
  /milo/i,
  /bournvita/i,
  /ovaltine/i,
  /evaporated.?milk/i,
  /condensed.?milk/i,
  /powdered.?milk/i,
  /egusi/i,
  /ogbono/i,
  /okro/i,
  /okra/i,
  /efo/i,
  /edikang.?ikong/i,
  /afang/i,
  /bitterleaf/i,
  /pepper.?soup/i,
  /jollof/i,
  /ofada/i,
  /coconut.?rice/i,
  /fried.?rice/i,
  /moi.?moi/i,
  /moinmoin/i,
  /akara/i,
  /kose/i,
  /ewa/i,
  /agoyin/i,
  /ugwu/i,
  /ugu/i,
  /ewedu/i,
  /water.?leaf/i,
  /scent.?leaf/i,
  /nchanwu/i,
  /uziza/i,
  /utazi/i,
  /ata.?rodo/i,
  /shombo/i,
  /tatashe/i,
  /iru/i,
  /dawadawa/i,
  /ogili/i,
  /ukpaka/i,
  /ugba/i,
  /agbalumo/i,
  /udara/i,
  /ube/i,
  /garden.?egg/i,
  /chin.?chin/i,
  /puff.?puff/i,
  /buns/i,
  /samosa/i,
  /spring.?roll/i,
  /meat.?pie/i,
  /fish.?roll/i,
  /egg.?roll/i,
  /scotch.?egg/i,
  /zobo/i,
  /kunu/i,
  /kunun/i,
  /fura/i,
  /nono/i,
  /sobo/i,
  /peak.?milk/i,
  /three.?crowns/i,
  /carnation/i,
  /cowbell/i,
  /hollandia/i,
  /fan.?yogurt/i,
  /fan.?yoghurt/i,
  /ukpo/i,
  /achi/i,
  /elubo/i,
  /akpu/i,
  /ogi/i,
  /pap/i,
  /semovita/i,
  /semolina/i,
  /lafun/i,
  /poundo/i,
  /tapioca/i,
  /water.?yam/i,
  /ponmo/i,
  /shaki/i,
  /cow.?foot/i,
  /cow.?leg/i,
  /cow.?skin/i,
  /gizzard/i,
  /tripe/i,
  /bush.?meat/i,
  /grasscutter/i,
  /snail/i,
  /prawn/i,
  /shrimp/i,
  /dry.?fish/i,
  /okporoko/i,
  /agbado/i,
  /ewa.?agoyin/i,
  /soya.?bean/i,
  /soybean/i,
  /tiger.?nut/i,
  /asala/i,
  /walnut/i,
  /cashew/i,
  /palm.?oil/i,
  /red.?oil/i,
  /groundnut.?oil/i,
  /coconut.?oil/i,
  /canola.?oil/i,
  /vegetable.?oil/i,
  /blue.?band/i,
  /simas/i,
  /dodo/i,
  /biko/i,
  /moimoi/i,
  /ekuru/i,
  /gbegiri/i,
  /ewedu.?soup/i,
  /egusi.?soup/i,
  /vegetable.?soup/i,
  /draw.?soup/i,
  /melon.?soup/i,
  /melon.?seed/i,
  /bitter.?leaf/i,
  /curry.?leaf/i,
  /spinach/i,
  /green/i,
  /fluted.?pumpkin/i,
  /pumpkin.?leaf/i,
  /red.?oil/i,
  /palm.?nut/i,
  /banga/i,
  /starch/i,
  /cassava.?flour/i,
  /yam.?flour/i,
  /plantain.?flour/i,
  /soya.?flour/i,
  /wheat.?flour/i,
  /rice.?flour/i,
  /corn.?flour/i,
  /golden.?morn/i,
  /cornflakes/i,
  /custard/i,
  /fresh.?milk/i,
  /tinned.?tomato/i,
  /gino/i,
  /de Rica/i,
  /pepper.?soup.?spice/i,
  /suya/i,
  /asun/i,
  /kilishi/i,
  /balangu/i,
  /nkwobi/i,
  /isiewu/i,
  /abacha/i,
  /ugba.?salad/i,
  /ncha/i,
  /antioxidant/i,
  /emulsifier/i,
  /stabilizer/i,
  /stabiliser/i,
  /thickener/i,
  /humectant/i,
  /bulking.?agent/i,
  /raising.?agent/i,
  /anti.?caking/i,
  /glazing.?agent/i,
  /firming.?agent/i,
  /flavour/i,
  /flavor/i,
  /colour/i,
  /color/i,
  /sweetener/i,
  /dietary.?fib/i,
  /dietary.?fibe/i,
  /enzym/i,
  /protein/i,
  /carbohydrate/i,
  /ingredient/i,
  /additive/i,
  /lactose/i,
  /gluten/i,
  /wheat/i,
  /maize/i,
  /corn/i,
  /barley/i,
  /oat/i,
  /rye/i,
  /millet/i,
  /sorghum/i,
  /yeast/i,
  /baking.?soda/i,
  /baking.?powder/i,
  /mono.?and.?diglyceride/i,
  /sodium/i,
  /potassium/i,
  /calcium/i,
  /magnesium/i,
  /serving/i,
  /per.?serving/i,
  /daily.?value/i,
  /energy/i,
  /kcal/i,
  /kjoule/i,
  /manufactured/i,
  /distributed/i,
  /imported/i,
  /exported/i,
  /packed/i,
  /net.?weight/i,
  /best.?before/i,
  /expir/i,
  /batch/i,
  /lot.?no/i,
  /meal/i,
  /product/i,
  /pack/i,
  /bottle/i,
  /can/i,
  /sachet/i,
  /tin/i,
  /safe/i,
  /healthy/i,
  /bad/i,
  /good/i,
  /harmful/i,
]

export function sanitizeInput(input: string): string {
  return input.replace(/[<>]/g, "").replace(/[{}`$]/g, "").trim()
}

export function runGuardrail(input: string, hasSessionHistory = false): GuardrailResult {
  const cleanInput = sanitizeInput(input)

  const isInjection = OUT_OF_SCOPE_PATTERNS.some((p) => p.test(cleanInput))
  if (isInjection) return { allowed: false }

  if (hasSessionHistory) {
    const isUnrelated = UNRELATED_TOPICS.some((p) => p.test(cleanInput))
    if (isUnrelated) return { allowed: false }
    return { allowed: true }
  }

  const isBrand = FOOD_BRANDS.some((p) => p.test(cleanInput))
  if (isBrand) return { allowed: true }

  const isFoodRelated = FOOD_KEYWORDS.some((p) => p.test(cleanInput))
  if (!isFoodRelated) return { allowed: false }

  return { allowed: true }
}
